using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraFollow : MonoBehaviour
{
    [SerializeField] private Transform _target;
    [SerializeField] private Vector3 _offset;
    [SerializeField] private float smoothFactor = 2.0f;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void FixedUpdate()
    {
        Vector3 position = _target.position + _offset;
        Vector3 smoothPosition = Vector3.Lerp(transform.position, position, smoothFactor);
        transform.position = smoothPosition;
    }
}
